Print output local coordinates
emersion/slurp pull request #111
Opened 2022-08-14 13:47 UTC by columbarius

With the '-x' flag slurp will calculate the x and y coordinates relative
to the position of the output the selection starts on (upper left corner).
If the selection spans over multiple outputs it will be cropped to the
intersection with the output.

2022-08-15 07:58 UTC, emersion commented
I'd rather not add a global flag if we are to add such a feature. I'd prefer new `%` sequences.

2022-08-15 08:07 UTC, columbarius commented
Are `%X, %Y` fine?

2022-08-22 18:46 UTC, columbarius commented
gentle ping

2022-10-05 13:09 UTC, emersion commented on main.c
> +		print_formatted_result(stream, &state, &state.result, format);
If we're passing the state, no need to pass the result separately.

2022-10-05 13:09 UTC, emersion commented on slurp.1.scd
> +%X  The x-coordinate of the selection with coordinates relative to the output
Nit: should use a tab for proper alignment.

2022-10-05 13:09 UTC, emersion commented on slurp.1.scd
> +%Y  The y-coordinate of the selection with coordinates relative to the output
Ditto

2022-10-05 13:09 UTC, emersion requested changes
Overall looks good, just a few finishing touches

2022-10-07 16:27 UTC, emersion approved these changes
LGTM, thanks!

2022-10-07 16:27 UTC, merged

2022-10-07 19:17 UTC, WhyNotHugo commented
Can we have a new release with this change?