Makes a single click equivalent to a point selection
emersion/slurp pull request #129
Opened 2023-05-25 10:48 UTC by fobekyo

This is useful to create a maim like screenshot utility where a single where a single click can select a window and a drag action selects a rectangle. In order to still have a way to cancel slurp with the mouse, buttons besides the left key act like escape.

2023-05-25 15:51 UTC, emersion commented
Does the -p option do what you want?

2023-05-25 16:19 UTC, fobekyo commented
The p option does not achieve the same goal because it requires to specify in advance if I want to have a point or an area selection

2023-12-03 16:19 UTC, pacien requested changes
I've hit the same need to obtain either a rectangular or point selection from the same call of `slurp` for the same use case (selecting a rectangle or a window for screenshotting).

This is distinct from `-p` which prevents the selection of a rectangle in the UI. Here we want both possibilities with the same call.

The responsibility to deal with either a `1x1` or bigger selection is left to the caller when both are enabled. Nothing hard.

Regarding the right click action to cancel selection: please mention it in the documenation (manual page).

2024-02-01 20:19 UTC, Funestia commented on main.c
> +		case 272: //left mouse button
whats wrong about the nested switch in this instance?

2025-11-26 21:18 UTC, b0o commented
This would be really nice, +1. My use-case is, in Niri, to allow the user to either pick a window by point-clicking, or a specific bounding box by click-dragging. I've tested this and it does exactly what I want. If there's concern about breaking backwards compatibility, perhaps this behavior could be moved behind a flag.

2025-11-27 07:53 UTC, tmccombs requested changes
One small thing that should be improved but otherwise looks good.

2025-11-27 07:53 UTC, tmccombs commented on main.c
> +	default: //right mouse button
This could also be a middle mouse button, or one of the forward/backward mouse buttons, etc. 

Which I think is probably fine implementation-wise, but the comment should at least be changed to reflect that. 

I'll also note that currently, it is possible to select with right click instead of with left click, but I don't think that is intentional.

2025-11-27 09:08 UTC, fuyarovh commented on main.c
> +	default: //right mouse button
Before this change you could cancel a selection with a single click. Because this is no longer possible with this change I changed other mouse buttons to mean cancel but I can change that if that behaviour is not wanted.

2025-11-27 17:36 UTC, tmccombs approved these changes

2025-11-27 17:36 UTC, merged